version: "3.5"
    
services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TimeLogger
    volumes:
      - pgdata:/var/lib/postgresql/data

  dotnet:
    depends_on: [ "postgres" ]
    build:
       context: .
    ports:
      - 80:5000
    restart: always
    environment:
       - ASPNETCORE_Environment=Prod
       - TimeLogger_ConnectionString__PostgresServer=postgres
       - TimeLogger_ConnectionString__PostgresUser=postgres
       - TimeLogger_ConnectionString__PostgresPassword=root

    volumes:
      - ./logs:/app/logs

volumes:
  pgdata: