version: "3.5"
    
services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TimeLogger
    volumes:
      - pgdata:/var/lib/postgresql/data

  dotnet:
    depends_on: [ "postgres" ]
    build:
       context: .
    ports:
      - 80:5000
    restart: always
    environment:
       - TZ=Australia/Melbourne
       - ASPNETCORE_Environment=Prod
       - TimeLogger_ConnectionString__PostgresServer=postgres
       - TimeLogger_ConnectionString__PostgresUser=postgres
       - TimeLogger_ConnectionString__PostgresPassword=root
       - "TimeLogger_PublicHolidaySettings__ApiUrl=https://data.gov.au/data/api/3/action/datastore_search"
       - TimeLogger_PublicHolidaySettings__ResourceId=c4163dc4-4f5a-4cae-b787-43ef0fcf8d8b
       - TimeLogger_PublicHolidaySettings__State=vic

    volumes:
      - ./logs:/app/logs

volumes:
  pgdata: