version: "3.5"
    
services:
  postgres-local:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TimeLogger
    volumes:
      - data:/var/lib/postgresql/data

  dotnet:
    depends_on: [ "postgres-local" ]
    build:
       context: .
    ports:
      - 80:5000
    restart: always
    environment:
       - ASPNETCORE_Environment=Prod
       - TimeLogger_ConnectionString="Server=postgres-local;Database=TimeLogger;User Id=postgres;Password=root"
    volumes:
      - ./logs:/app/logs

volumes:
  data: